version: "3.2"

networks:
  stack:

services:

  apigateway:
    image: ${REG_APIGATEWAY}${IMAGE_APIGATEWAY}:${TAG_APIGATEWAY}
    ports:
      - "5555:5555"
      - "9072:9072"
    networks:
      - stack
  
  config_changepassword:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      apigw_connect_host: apigateway
      apigw_connect_port: "5555"
      apigw_connect_user: Administrator
      apigw_connect_password: "somethingnew"
      apigw_changepassword_enabled: "true"
      apigw_changepassword_old: "manage"
    networks:
      - stack

  config_loadbalancerurls:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      apigw_connect_host: apigateway
      apigw_connect_port: "5555"
      apigw_connect_user: Administrator
      apigw_connect_password: "somethingnew"
      apigw_settings_lburls_configure: "true"
      apigw_settings_lburls_http_url: "http://externallb1:80"
      apigw_settings_lburls_https_url: "https://externallb1:443"
      apigw_settings_lburls_websocket_url: "ws://externallb1"
      apigw_settings_lburls_http_url_alt1: "http://externallb2"
      apigw_settings_lburls_https_url_alt1: "https://externallb2"
      apigw_settings_lburls_websocket_url_alt1: "ws://externallb2"
      apigw_settings_lburls_webapp_url: "http://externallb"
    networks:
      - stack