version: "3.2"

networks:
  stack:

services:

  apigateway:
    image: ${REG_APIGATEWAY}${IMAGE_APIGATEWAY}:${TAG_APIGATEWAY}
    ports:
      - "5555:5555"
      - "9072:9072"
    networks:
      - stack
  
  devportal:
    image: ${REG_DEVPORTAL}${IMAGE_DEVPORTAL}:${TAG_DEVPORTAL}
    ports:
      - "8083:8083"
    environment: 
      SPRING_ELASTICSEARCH_REST_URIS: "http://elasticsearch:9200"
    networks:
      - stack

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$TAG_ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.port=9200
      - transport.port=9300
    networks:
      - stack

  config_changepassword:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      changepassword_enabled: "true"
      changepassword_old: "manage"
    networks:
      - stack

  config_loadbalancerurls:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      settings_lburls_configure: "true"
      settings_lburls_http_urls: "http://externallb1:80;http://externallb2;http://externallb3"
      settings_lburls_https_urls: "https://externallb1:443;https://externallb2:443;https://externallb3:443"
      settings_lburls_websocket_url: "ws://externallb1;ws://externallb2;ws://externallb3"
      settings_lburls_webapp_url: "http://externallb"
    networks:
      - stack

  config_coresettings:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      settings_core_configure: "true"
      settings_core_watts: watt.server.cachemanager.connectTimeout=300000 watt.net.timeout=600 watt.net.clientKeepaliveUsageLimit=10000000 watt.server.threadPoolMin=50 watt.server.threadPool=1000 watt.server.control.serverThreadThreshold=50 watt.security.ssl.cacheClientSessions=true watt.net.maxClientKeepaliveConns=500 watt.security.ssl.resumeClientSessions=true
      settings_core_extended: "events.reportingQueue.size=5000 events.collectionPool.minThreads=2 events.collectionPool.maxThreads=32 events.reportingPool.minThreads=4 events.reportingPool.maxThreads=16 eventsRefreshInterval=60s events.collectionQueue.size=10000000"
    networks:
      - stack

  config_keystore:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    volumes:
      - ../resources/certs:/certs:ro
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      settings_keystore_configure: "true"
      settings_keystore_filepath: /certs/apigateway-p12.jks
      settings_keystore_name: "Custom_SSL_Keystore"
      settings_keystore_description: "My custom keystore for SSL"
      settings_keystore_password: "manage"
      settings_keystore_keyalias: "certificate"
      settings_keystore_keyalias_password: "manage"
    networks:
      - stack
  
  config_truststore:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    volumes:
      - ../resources/certs:/certs:ro
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      settings_truststore_configure: "true"
      settings_truststore_filepath: /certs/apigateway-truststore.jks
      settings_truststore_name: "Custom_SSL_Truststore"
      settings_truststore_description: "My custom truststore"
      settings_truststore_password: "manage"
    networks:
      - stack

  config_ssl_inbound_outbound_connections:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      settings_ssl_inbound_outbound_configure: "true"
      settings_ssl_inbound_keystore_name: "Custom_SSL_Keystore"
      settings_ssl_inbound_keystore_keyalias: "certificate"
      settings_ssl_inbound_truststore_name: "Custom_SSL_Truststore"
      settings_ssl_outbound_keystore_name: "Custom_SSL_Keystore"
      settings_ssl_outbound_keystore_keyalias: "certificate"
      settings_ssl_outbound_truststore_name: "Custom_SSL_Truststore"
    networks:
      - stack

## TODO: do as part of the port configs

  # config_default_ssl_port:
  #   image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
  #   environment: 
  #     configurator_debug: "true"
  #     connect_host: apigateway
  #     connect_port: "5555"
  #     connect_user: Administrator
  #     connect_password: "somethingnew"
  #     settings_ssl_runtimeport_configure: "true"
  #     settings_ssl_runtimeport_port: "5543"
  #     settings_ssl_runtimeport_keystore_name: "Custom_SSL_Keystore"
  #     settings_ssl_runtimeport_keystore_keyalias: "certificate"
  #     settings_ssl_runtimeport_truststore_name: "Custom_SSL_Truststore"
  #   networks:
  #     - stack
  
  # config_new_ssl_port:
  #   image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
  #   environment: 
  #     configurator_debug: "true"
  #     connect_host: apigateway
  #     connect_port: "5555"
  #     connect_user: Administrator
  #     connect_password: "somethingnew"
  #     settings_ssl_runtimeport_configure: "true"
  #     settings_ssl_runtimeport_port: "6643"
  #     settings_ssl_runtimeport_keystore_name: "Custom_SSL_Keystore"
  #     settings_ssl_runtimeport_keystore_keyalias: "certificate"
  #     settings_ssl_runtimeport_truststore_name: "Custom_SSL_Truststore"
  #   networks:
  #     - stack

  config_promotion_stages:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    volumes:
      - ../resources/certs:/certs:ro
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_promotions_stages_configure: "true"
      data_promotions_stages_0_name: promotion1
      data_promotions_stages_0_description: description1
      data_promotions_stages_0_url: http://gateway1:5555
      data_promotions_stages_0_username: testuser1
      data_promotions_stages_0_password: password1
      data_promotions_stages_0_keystoreAlias: ""
      data_promotions_stages_0_keyAlias: ""
      data_promotions_stages_1_name: promotion2
      data_promotions_stages_1_description: description2
      data_promotions_stages_1_url: http://gateway2:5555
      data_promotions_stages_1_username: testuser2
      data_promotions_stages_1_password: password2
      data_promotions_stages_1_keystoreAlias: ""
      data_promotions_stages_1_keyAlias: ""
    networks:
      - stack

  config_portalgateway:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      settings_portalgateway_configure: "true"
      settings_portalgateway_configure_ignore_errors: "true"
      settings_portalgateway_name: API PortalGateway Config
      settings_portalgateway_description: API PortalGateway Configuration
      settings_portalgateway_version: "1.0"
      settings_portalgateway_stagename: "DEV"
      settings_portalgateway_gateway_url: "http://apigateway:5555"
      settings_portalgateway_gateway_username: "Administrator"
      settings_portalgateway_gateway_password: "somethingnew"
      settings_portalgateway_portaltype: devportal
      settings_portalgateway_devportal_tenant: default
      settings_portalgateway_devportal_url: "http://devportal:8083/portal"
      settings_portalgateway_devportal_username: "Administrator"
      settings_portalgateway_devportal_password: "manage"
    networks:
      - stack

  config_saml:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    volumes:
      - ../resources/certs:/certs:ro
      - ../resources/saml/idpmetadata.xml:/configs/idpmetadata.xml:ro
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      settings_keystore_configure: "true"
      settings_keystore_filepath: /certs/saml-p12.jks
      settings_keystore_name: "SAMLSelfSignedKeystore"
      settings_keystore_description: "My custom keystore for SAML"
      settings_keystore_password: "manage"
      settings_keystore_keyalias: "certificate"
      settings_keystore_keyalias_password: "manage"
      settings_saml_configure: "true"
      settings_saml_sp_id: "webmethods-apigateway-saml-client"
      settings_saml_keystore_alias: "SAMLSelfSignedKeystore"
      settings_saml_keystore_default_key_alias: certificate
      settings_saml_redirect_host: "http://mygateway:9072"
      settings_saml_usebydefault: "false"
      settings_saml_idpmetadata_localfilepath: "/configs/idpmetadata.xml"
      settings_saml_idpmetadata_content_b64encoded: ""
      # Fetching the IDP metadata rom url is preferred but we don't have an IDP here...refer to another full SAML test!
      # settings_saml_idpmetadata_url: http://myidp/saml/descriptor
      settings_saml_userprofilemapping_firstname: firstName
      settings_saml_userprofilemapping_lastname: lastName
      settings_saml_userprofilemapping_email: email
      settings_saml_group_attributes: roles;Role
      settings_saml_groups_to_apigateway_groups: apigateway-admin=API-Gateway-Administrators;apigateway-apiprovider=API-Gateway-Providers;apigateway-user=Everybody
    networks:
      - stack

  config_import_archives:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    volumes:
      - ../resources/sampleapis_archives:/imports:ro
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_archives_import: "true"
      data_archives_1_path: "/imports/apigw-archive-api-bookstore-1.0.zip"
      data_archives_1_overwrite: "apis,policies,policyactions"
      data_archives_1_fixingMissingVersions: "true"
      data_archives_1_preserveAssetState: "true"
      data_archives_2_path: "/imports/apigw-archive-api-uszip-1.0.zip"
      data_archives_2_overwrite: "apis,policies,policyactions"
      data_archives_2_fixingMissingVersions: "true"
      data_archives_2_preserveAssetState: "true"
    networks:
      - stack

  config_import_archives_nothing:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    volumes:
      - ../resources/sampleapis_archives:/imports:ro
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_archives_import: "true"
    networks:
      - stack

  config_aliases:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_aliases_configure: "true"
      data_aliases_0_name: name1
      data_aliases_0_description: desc1
      data_aliases_0_type: simple
      data_aliases_0_value: val1
      data_aliases_0_stage: stag1
      data_aliases_1_name: name2
      data_aliases_1_description: desc2
      data_aliases_1_type: simple
      data_aliases_1_value: val2
      data_aliases_1_stage: stag2
      data_aliases_2_name: endpointname3
      data_aliases_2_description: endpoint alias
      data_aliases_2_type: endpoint
      data_aliases_2_stage: stag2
      data_aliases_2_endPointURI: http://test.local
    networks:
      - stack

  config_aliases_nothing:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_aliases_configure: "true"
    networks:
      - stack

  config_plans:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_plans_configure: "true"
      data_plans_0_name: "plan1"
      data_plans_0_version: "1.0"
      data_plans_1_name: "plan2"
      data_plans_1_version: "1.0"
      data_plans_2_name: "plan3"
      data_plans_2_version: "1.0"
    networks:
      - stack

  config_plans_nothing:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_plans_configure: "true"
    networks:
      - stack

  config_packages:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_packages_configure: "true"
      data_packages_0_name: "package1"
      data_packages_0_version: "1.0"
      data_packages_0_deprecated: "false"
      data_packages_0_active: "true"
      data_packages_0_lookup_apis: "bookstore:1.0 ; uszip:1.0"
      data_packages_0_lookup_plans: "plan1:1.0 ; plan2:1.0"
      data_packages_0_lookup_policies: ""
      data_packages_1_name: "package2"
      data_packages_1_version: "1.0"
      data_packages_1_deprecated: "false"
      data_packages_1_active: "true"
      data_packages_1_lookup_apis: "bookstore:1.0"
      data_packages_1_lookup_plans: "plan2:1.0 ; plan3:1.0"
      data_packages_1_lookup_policies: ""
    networks:
      - stack

  config_packages_deactivate:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_packages_status_update: "true"
      data_packages_0_name: "package1"
      data_packages_0_version: "1.0"
      data_packages_0_active: "false"
      data_packages_1_name: "package2"
      data_packages_1_version: "1.0"
      data_packages_1_active: "false"
    networks:
      - stack

## TODO: fix error when lookup apis is empty...
  config_applications:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_applications_configure: "true"
      data_applications_0_name: app1
      data_applications_0_version: "0.1"
      data_applications_0_description: app1 description
      data_applications_0_isSuspended: "false"
      data_applications_0_restrictViewAsset: "false"
      data_applications_0_lookup_apis: "bookstore:1.0 ; uszip:1.0"
      data_applications_1_name: app2
      data_applications_1_version: "0.2"
      data_applications_1_description: app2 description
      data_applications_1_isSuspended: "false"
      data_applications_1_restrictViewAsset: "false"
      data_applications_1_lookup_apis: "bookstore:1.0"
      data_applications_2_name: app3
      data_applications_2_version: "0.3"
      data_applications_2_description: app3 description
      data_applications_2_isSuspended: "false"
      data_applications_2_restrictViewAsset: "false"
      data_applications_2_lookup_apis: ""
    networks:
      - stack

  config_applications_deactivate:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_applications_status_update: "true"
      data_applications_0_name: app1
      data_applications_0_version: "0.1"
      data_applications_0_isSuspended: "true"
      data_applications_1_name: app2
      data_applications_1_version: "0.2"
      data_applications_1_isSuspended: "true"
      data_applications_2_name: app3
      data_applications_2_version: "0.3"
      data_applications_2_description: app3 description
      data_applications_2_isSuspended: "true"
    networks:
      - stack

  publish_apis:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_apis_publish: "true"
      data_apis_0_portalgateway_name: API PortalGateway Config
      data_apis_0_portalgateway_version: "1.0"
      data_apis_0_portalgateway_stageName: DEV
      data_apis_0_lookup_communities: "Public Community"
      data_apis_0_lookup_apis: "bookstore:1.0 ; uszip:1.0"
    networks:
      - stack

  publish_packages:
    image: ${REG_APIGATEWAY_CONFIGURATOR}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      data_packages_publish: "true"
      data_packages_0_portalgateway_name: API PortalGateway Config
      data_packages_0_portalgateway_version: "1.0"
      data_packages_0_portalgateway_stageName: DEV
      data_packages_0_lookup_communities: "Public Community"
      data_packages_0_lookup_packages: "package1:1.0 ; package2:1.0"
    networks:
      - stack