---
vars_apis_enabled: "{{ lookup('env', 'data_apis_configure') | default('false',true) }}"
vars_apis_ignore_errors: "{{ lookup('env', 'data_apis_configure_ignore_errors') | default(vars_default_ignore_errors,true) }}"

vars_apis_publish_groups_enabled: "{{ lookup('env', 'data_apis_publish') | default('false',true) }}"
vars_apis_publish_groups_ignore_errors: "{{ lookup('env', 'data_apis_publish_ignore_errors') | default(vars_default_ignore_errors,true) }}"

## finding the indices from the env vars
_apis_indices_finder_prefix: "data_apis_"
_apis_indices_finder_suffix: "_name"
_index_items_regex_pattern: "{{ common_index_items_regex_pattern | format( _apis_indices_finder_prefix, _apis_indices_finder_suffix) }}"

_apis_template_tags: "{{ (lookup('env', 'data_apis_%s_api_tags' | format(index_item)) | default('',true)).split(_string_list_separator)|map('trim')|select()|list }}"
_apis_template:
      name: "{{ lookup('env', 'data_apis_%s_name' | format(index_item)) | default('',true) }}"
      version: "{{ lookup('env', 'data_apis_%s_version' | format(index_item)) | default('',true) }}"
      apiDescription: "{{ lookup('env', 'data_apis_%s_description' | format(index_item)) | default('',true) }}"
      maturityState: "{{ lookup('env', 'data_apis_%s_maturity_state' | format(index_item)) | default('',true) }}"
      apiGroups: "{{ (lookup('env', 'data_apis_%s_api_groups' | format(index_item)) | default('',true)).split(_string_list_separator)|map('trim')|select()|list }}"
      apiDefinition:
            apiTags: "{{ _apis_template_tags }}"

# APIs to publish
_apis_publish_indices_finder_prefix: "data_apis_"
_apis_publish_indices_finder_suffix: "_portalgateway_name"
_apis_publish_indices_regex_pattern: "{{ common_index_items_regex_pattern | format( _apis_publish_indices_finder_prefix, _apis_publish_indices_finder_suffix) }}"
_apis_publish_template:
      lookup_portalGatewayId:
            name: "{{ lookup('env', 'data_apis_%s_portalgateway_name' | format(index_item)) | default('',true) }}"
            version: "{{ lookup('env', 'data_apis_%s_portalgateway_version' | format(index_item)) | default('',true) }}"
            stageName: "{{ lookup('env', 'data_apis_%s_portalgateway_stageName' | format(index_item)) | default('',true) }}"

# these will be added dynamically to the object

## map to field lookup_communityIds
# input format is [ community1;community2;community3 ]
# output format is a list:
# - name: "community1"
# - name: "community2"
# - name: "community3"
_apis_publish_lookup_communities: "{{ lookup('env', 'data_apis_%s_lookup_communities' | format(index_item)) | default('',true) }}"

## map to field lookup_apiIds
# input format is [ name1:version1;name2:version2 ]
# output format is list:
# - name: "name1"
#   version: "version1"
# - name: "name2"
#   version: "version2"
_apis_publish_lookup_apis: "{{ lookup('env', 'data_apis_%s_lookup_apis' | format(index_item)) | default('',true) }}"

# FYI sample payload expected by the publish role
# _publish_apis_list:
#   - lookup_portalGatewayId:
#   name: API PortalGateway Config
#   stageName: DEV
#   version: "1.0"
#     lookup_communityIds:
#   - name: Public Community
#     lookup_apiIds:
#   - name: bookstore
#     version: "1.0"
#   - name: uszip
#     version: "1.0"

## activate apis (or not)
_apis_activate_template:
      name: "{{ lookup('env', 'data_apis_%s_name' | format(index_item)) | default('',true) }}"
      version: "{{ lookup('env', 'data_apis_%s_version' | format(index_item)) | default('',true) }}"
      active: "{{ lookup('env', 'data_apis_%s_active' | format(index_item)) | default('',true) }}"
