
---

vars_archive_imports_enabled: "{{ lookup('env', 'data_archives_import') | default('false',true) }}"
vars_archive_imports_ignore_errors: "{{ lookup('env', 'data_archives_import_ignore_errors') | default(vars_default_ignore_errors,true) }}"
vars_archive_imports_autozip_enabled: "{{ lookup('env', 'data_archives_import_autozip_enabled') | default('false',true) }}"

_archives_indices_finder_prefix: "data_archives_"
_archives_indices_finder_suffix: "_path"
_index_items_regex_pattern: "{{ common_index_items_regex_pattern | format( _archives_indices_finder_prefix, _archives_indices_finder_suffix) }}"

## archives to import into gateway
_archives_template:
  path: "{{ lookup('env', 'data_archives_%s_path'| format(index_item)) | default('',true) }}"
  overwrite: "{{ lookup('env', 'data_archives_%s_overwrite'| format(index_item)) | default('',true) }}"
  fixingMissingVersions: "{{ lookup('env', 'data_archives_%s_fixingMissingVersions'| format(index_item)) | default('',true) }}"
  preserveAssetState: "{{ lookup('env', 'data_archives_%s_preserveAssetState'| format(index_item)) | default('',true) }}"