---

vars_apigw_plans_enabled: "{{ lookup('env', 'apigw_configure_plans') | default('false',true) }}"
vars_apigw_packages_enabled: "{{ lookup('env', 'apigw_configure_packages') | default('false',true) }}"

vars_apigw_plans_ignore_errors: "{{ lookup('env', 'apigw_configure_plans_ignore_errors') | default(vars_apigw_default_ignore_errors,true) }}"
vars_apigw_packages_ignore_errors: "{{ lookup('env', 'apigw_configure_packages_ignore_errors') | default(vars_apigw_default_ignore_errors,true) }}"

# api packages to add or update
# the following attributes with "custom_" will be transformed to corresponding attributes of internal ids:
# - custom_apiIdsByFilter --> apiIds
# - custom_planIdsByFilter --> planIds
# - custom_policyIdsByFilter --> policyIds
vars_apigw_packages:
  - name: Swag Pack Complete
    version: "1.0"
    deprecated: false
    custom_apiIdsByFilter:
      - name: "bookstore"
        version: "1.0"
      - name: "uszip"
        version: "1.0"
      - name: "covid"
        version: "1.0"
      - name: "SAGTours"
        version: "1.0"
    custom_planIdsByFilter:
      - name: "gold"
        version: "1.0"
      - name: "silver"
        version: "1.0"
      - name: "bronze"
        version: "1.0"
    publishedPortals: []
    custom_policyIdsByFilter: []
    active: true
  - name: Swag Pack Bookstore
    version: "1.0"
    deprecated: false
    custom_apiIdsByFilter:
      - name: "bookstore"
        version: "1.0"
    custom_planIdsByFilter:
      - name: "gold"
        version: "1.0"
      - name: "silver"
        version: "1.0"
      - name: "bronze"
        version: "1.0"
    publishedPortals: []
    custom_policyIdsByFilter: []
    active: true
  - name: Swag Pack UsZip
    version: "1.0"
    deprecated: false
    custom_apiIdsByFilter:
      - name: "uszip"
        version: "1.0"
    custom_planIdsByFilter:
      - name: "gold"
        version: "1.0"
      - name: "silver"
        version: "1.0"
      - name: "bronze"
        version: "1.0"
    publishedPortals: []
    custom_policyIdsByFilter: []
    active: true
  - name: Swag Pack CovidReports
    version: "1.0"
    deprecated: false
    custom_apiIdsByFilter:
      - name: "covid"
        version: "1.0"
    custom_planIdsByFilter:
      - name: "gold"
        version: "1.0"
      - name: "silver"
        version: "1.0"
      - name: "bronze"
        version: "1.0"
    publishedPortals: []
    custom_policyIdsByFilter: []
    active: true

vars_apigw_packages_update_final_status:
  - name: Swag Pack Complete
    version: "1.0"
    active: false
  - name: Swag Pack Bookstore
    version: "1.0"
    active: false
  - name: Swag Pack UsZip
    version: "1.0"
    active: false
  - name: Swag Pack CovidReports
    version: "1.0"
    active: false

# api plans to add or update
vars_apigw_plans:
  - name: gold
    version: "1.0"
    deprecated: false
    isProtected: false
    policiesNames: []
    cost:
      currency:
      value:
      duration:
    quota:
      enforcementPolicyName: ""
    protected: false
  - name: silver
    version: "1.0"
    deprecated: false
    isProtected: false
    policiesNames: []
    cost:
      currency:
      value:
      duration:
    quota:
      enforcementPolicyName: ""
    protected: false
  - name: bronze
    version: "1.0"
    deprecated: false
    isProtected: false
    policiesNames: []
    cost:
      currency:
      value:
      duration:
    quota:
      enforcementPolicyName: ""
    protected: false
