# enable / disable the config items
vars_webmethods_apigateway_samlconfigs_enabled: "{{ lookup('env', 'env_apigateway_saml_configure_samlconfigs') | default('false',true) }}"

# ignore errors or not for each of the config items (defaults to vars_webmethods_apigateway_default_ignore_errors)
vars_webmethods_apigateway_samlconfigs_ignore_errors: "{{ lookup('env', 'env_apigateway_saml_configure_samlconfigs_ignore_errors') | default(vars_webmethods_apigateway_default_ignore_errors,true) }}"

######################################################################
## the saml certs for encryption / signing
######################################################################
vars_saml_keystore_filepath: "{{ lookup('env', 'env_apigateway_saml_keystore_filepath') | default('',true) }}"
vars_saml_keystore_filename: "{{ vars_saml_keystore_filepath | basename }}"
vars_saml_keystore_name: "{{ lookup('env', 'env_apigateway_saml_keystore_name') | default((vars_saml_keystore_filename | splitext)[0],true) }}"
vars_saml_keystore_keyalias_name: "{{ lookup('env', 'env_apigateway_saml_keystore_keyalias') | default('',true) }}"

vars_saml_keystore:
  filepath: "{{ vars_saml_keystore_filepath }}"
  filename: "{{ vars_saml_keystore_filename }}"
  name: "{{ vars_saml_keystore_name }}"
  type: "{{ lookup('env', 'env_apigateway_saml_keystore_type') | default('JKS',true) }}"
  provider: "{{ lookup('env', 'env_apigateway_saml_keystore_provider') | default('SUN',true) }}"
  description: "{{ lookup('env', 'env_apigateway_saml_keystore_description') | default('APIGateway keystore',true) }}"
  password: "{{ lookup('env', 'env_apigateway_saml_keystore_password') | default('',true) }}"
  keyalias: "{{ vars_saml_keystore_keyalias_name }}"
  keyalias_password: "{{ lookup('env', 'env_apigateway_saml_keystore_keyalias_password') | default('',true) }}"

## apigateway keystore details
vars_rest_webmethods_apigateway_saml_keystore:
  keyStoreName: "{{ vars_saml_keystore.name }}"
  keyStoreType: "{{ vars_saml_keystore.type }}"
  keyStoreProvider: "{{ vars_saml_keystore.provider }}"
  keyStorePassword: "{{ vars_saml_keystore.password | b64encode }}"
  uploadFileName: "{{ vars_saml_keystore.filename }}"
  keyStoreDescription: "{{ vars_saml_keystore.description }}"
  fileContent: "@{{ vars_saml_keystore.filepath }}"
  isPwdBase64Encoded: "true"

# this is for the aliases inside the keystore
## pkAliasesList: Comma separated list of alias names in the uploaded keystore file.
## pkPasswordsList: Comma separated list of passwords in the same order as the aliases specified in pkAliasesList. If a particular key alias does not have a password, it is denoted by space.
## nullPKpasswds: Comma separated list of boolean values (true/false) indicating whether the particular alias has a password or not in the same order as the aliases specified in pkAliasesList. For each key alias, true indicates that the key alias does not have a password and false indicates that it does have a password.
vars_rest_webmethods_apigateway_saml_keystore_keyalias_list:
  - keyStoreName: "{{ vars_saml_keystore.name }}"
    nullPKpasswds: "false"
    isPwdBase64Encoded: "false"
    bitarray: "1"
    pkAliasesList: "{{ vars_saml_keystore.keyalias }}"
    pkPasswordsList: "{{ vars_saml_keystore.keyalias_password }}"

######################################################################
## the saml settings
######################################################################

# if set, it will automatically put the content of the file into the idpMetadataContent field
vars_saml_idpmetadata_localfilepath: "{{ lookup('env', 'env_apigateway_saml_idpmetadata_localfilepath') | default('',true) }}"

# space separated values to create content into groupMapping.groupAttributes
vars_saml_group_attributes: "{{ lookup('env', 'env_apigateway_saml_group_attributes') | default('',true) }}"

# space separated key/value pairs to create content into groupMapping.attributeToGroupMap
vars_saml_groups_to_apigateway_groups: "{{ lookup('env', 'env_apigateway_saml_groups_to_apigateway_groups') | default('',true) }}"

# rest call payload
vars_rest_webmethods_apigateway_saml_settings:
  saml_enabled: "true"
  saml_sp_id: "{{ lookup('env', 'env_apigateway_saml_sp_id') | default('webmethods-apigateway',true) }}"
  saml_redirect: "{{ lookup('env', 'env_apigateway_saml_redirect_host') }}/apigatewayui/saml/SSO"
  saml_authreq_signed:  "{{ lookup('env', 'env_apigateway_saml_authreq_signed') | default('true',true) }}"
  saml_assertion_signed: "{{ lookup('env', 'env_apigateway_saml_assertion_signed') | default('true',true) }}"
  keystoreAlias: "{{ vars_saml_keystore_name }}"
  saml_defaultkey_alias: "{{ vars_saml_keystore_keyalias_name }}"
  saml_encrypkey_alias: "{{ vars_saml_keystore_keyalias_name }}"
  saml_signkey_alias: "{{ vars_saml_keystore_keyalias_name }}"
  useSSOLoginByDefault: "{{ lookup('env', 'env_apigateway_saml_usebydefault') | default('false',true) }}"
  idpMetadataContent: "{{ lookup('env', 'env_apigateway_saml_idpmetadata_content_b64encoded') | default('',true) }}"
  idpFilename: "{{ lookup('env', 'env_apigateway_saml_idpmetadata_filename') | default('',true) }}"
  idpUrl: "{{ lookup('env', 'env_apigateway_saml_idpmetadata_url') | default('',true) }}"
  userProfileMapping:
    firstName: "{{ lookup('env', 'env_apigateway_saml_userprofilemapping_firstname') | default('firstName',true) }}"
    lastName: "{{ lookup('env', 'env_apigateway_saml_userprofilemapping_lastname') | default('lastName',true) }}"
    emailAddresses: "{{ lookup('env', 'env_apigateway_saml_userprofilemapping_email') | default('email',true) }}"
  # this section is created automatically from the string variables above
  # groupMapping:
  #   groupAttributes:
  #     - roles
  #     - Role
  #   attributeToGroupMap:
  #     apigateway-admin: API-Gateway-Administrators
  #     apigateway-apiprovider: API-Gateway-Providers
  #     apigateway-user: Everybody