---

vars_users_enabled: "{{ lookup('env', 'settings_users_configure') | default('false',true) }}"
vars_users_ignore_errors: "{{ lookup('env', 'settings_users_configure_ignore_errors') | default(vars_default_ignore_errors,true) }}"

_users_indices_finder_prefix: "settings_users_"
_users_indices_finder_suffix: "_loginid"
_index_items_regex_pattern: "{{ common_index_items_regex_pattern | format( _users_indices_finder_prefix, _users_indices_finder_suffix) }}"

_users_template:
  loginId: "{{ lookup('env', 'settings_users_%s_loginid' | format(index_item)) | default('',true) }}"
  firstName: "{{ lookup('env', 'settings_users_%s_firstname' | format(index_item)) | default('',true) }}"
  lastName: "{{ lookup('env', 'settings_users_%s_lastname' | format(index_item)) | default('',true) }}"
  password: "{{ lookup('env', 'settings_users_%s_password' | format(index_item)) | default('',true) }}"
  emailAddresses: "{{ (lookup('env', 'settings_users_%s_emails' | format(index_item)) | default('',true)).split(';')|map('trim')|select()|list }}"
  allowDigestAuth: "{{ lookup('env', 'settings_users_%s_allowDigestAuth' | format(index_item)) | default('false',true) }}"
  active: "{{ lookup('env', 'settings_users_%s_active' | format(index_item)) | default('true',true) }}"
  language: "{{ lookup('env', 'settings_users_%s_language' | format(index_item)) | default('en',true) }}"