---

vars_loadbalancer_enabled: "{{ lookup('env', 'settings_lburls_configure') | default('false',true) }}"
vars_loadbalancer_ignore_errors: "{{ lookup('env', 'settings_lburls_configure_ignore_errors') | default(vars_default_ignore_errors,true) }}"

## load balancers

# _settings_lburls_http // _settings_lburls_https // _settings_lburls_websocket
# input format is "url1;url2;url3"
# output format is a simple list of string:
      # - url1
      # - url2
      # - url3
_settings_lburls_http_urls: "{{ (lookup('env', 'settings_lburls_http_urls') | default('',true)).split(_string_list_separator)|map('trim')|select()|list }}"
_settings_lburls_https_urls: "{{ (lookup('env', 'settings_lburls_https_urls') | default('',true)).split(_string_list_separator)|map('trim')|select()|list }}"
_settings_lburls_websocket_urls: "{{ (lookup('env', 'settings_lburls_websocket_urls') | default('',true)).split(_string_list_separator)|map('trim')|select()|list }}"

# input format is simple string
_settings_lburls_webapp_url: "{{ lookup('env', 'settings_lburls_webapp_url') | default('',true) }}"
