---

vars_apigw_ports_enabled: "{{ lookup('env', 'apigw_settings_ports_configure') | default('false',true) }}"
vars_apigw_ports_ignore_errors: "{{ lookup('env', 'apigw_settings_ports_configure_ignore_errors') | default(vars_apigw_default_ignore_errors,true) }}"

_apigw_ports_indices_finder_prefix: "apigw_settings_ports_"
_apigw_ports_indices_finder_suffix: "_name"
_apigw_ports_item_type: "{{ lookup('env', 'apigw_settings_ports_%s_type' | format(index_item)) | default('') }}"

## port types values: regular_http, regular_https, external_http, external_https, internal_http, internal_https, websocket
## is this needed: "provider": "webMethods"?

## apigateway HTTP port
## client_auth values: none, digest, requestKrb, requireKrb
_apigw_ports_template_http:
  port_type: regular_http
  port_enabled: "{{ lookup('env', 'apigw_settings_ports_%s_enabled' | format(index_item)) | default('',true) }}"
  port_detail:
    port: "{{ lookup('env', 'apigw_settings_ports_%s_port' | format(index_item)) | default('',true) }}"
    portAlias: "{{ lookup('env', 'apigw_settings_ports_%s_name' | format(index_item)) | default('',true) }}"
    portDescription: "{{ lookup('env', 'apigw_settings_ports_%s_description' | format(index_item)) | default('',true) }}"
    threadPool: "{{ lookup('env', 'apigw_settings_ports_%s_threadPool' | format(index_item)) | default('',true) }}"
    minThread: "{{ lookup('env', 'apigw_settings_ports_%s_threadPool_minthread' | format(index_item)) | default('',true) }}"
    maxThread: "{{ lookup('env', 'apigw_settings_ports_%s_threadPool_maxthread' | format(index_item)) | default('',true) }}"
    threadPriority: "{{ lookup('env', 'apigw_settings_ports_%s_threadpool_threadpriority' | format(index_item)) | default('',true) }}"
    maxQueue: "{{ lookup('env', 'apigw_settings_ports_%s_maxqueue' | format(index_item)) | default('',true) }}"
    keepAliveTimeout: "{{ lookup('env', 'apigw_settings_ports_%s_keepalivetimeout' | format(index_item)) | default('',true) }}"
    clientAuth: "{{ lookup('env', 'apigw_settings_ports_%s_clientauth' | format(index_item)) | default('',true) }}"

## apigateway HTTPS port
## this is the extra attributes on top of the regular HTTP port
## client_auth values: none, digest, requestKrb, requireKrb, request, require, idProvider
_apigw_ports_template_https:
  port_type: regular_https
  port_detail:
    keyStore: "{{ lookup('env', 'apigw_settings_ports_%s_keystore_name' | format(index_item)) | default('',true) }}"
    alias: "{{ lookup('env', 'apigw_settings_ports_%s_keystore_keyalias' | format(index_item)) | default('',true) }}"
    trustStore: "{{ lookup('env', 'apigw_settings_ports_%s_truststore_name' | format(index_item)) | default('',true) }}"

## apigateway WebSocket port
## client_auth values: just "basic" ?
_apigw_ports_template_websocket:
  port_type: websocket
  port_detail:
    idleTimeout: "{{ lookup('env', 'apigw_settings_ports_%s_idletimeout' | format(index_item)) | default('',true) }}"

## this gets added to any port
_apigw_ports_template_access_modes:
    access_mode:
      accessMode: "{{ lookup('env', 'apigw_settings_ports_%s_access_mode' | format(index_item)) | default('',true) }}"
      pkg: "{{ lookup('env', 'apigw_settings_ports_%s_access_mode_package' | format(index_item)) | default('WmRoot',true) }}"
      services: []
    ip_access_mode:
      ipAccessType: "{{ lookup('env', 'apigw_settings_ports_%s_ip_access_mode' | format(index_item)) | default('',true) }}"
      pkg: "{{ lookup('env', 'apigw_settings_ports_%s_ip_access_mode_package' | format(index_item)) | default('WmRoot',true) }}"
      hostsList: []