---

vars_truststores_enabled: "{{ lookup('env', 'settings_truststores_configure') | default('false',true) }}"
vars_truststores_ignore_errors: "{{ lookup('env', 'settings_truststores_configure_ignore_errors') | default(vars_default_ignore_errors,true) }}"

_truststores_indices_finder_prefix: "settings_truststores_"
_truststores_indices_finder_suffix: "_name"
_index_items_regex_pattern: "{{ common_index_items_regex_pattern | format( _truststores_indices_finder_prefix, _truststores_indices_finder_suffix) }}"

_truststores_template_filepath: "{{ lookup('env', 'settings_truststores_%s_filepath' | format(index_item)) | default('',true) }}"
_truststores_template_filename: "{{ _truststores_template_filepath | basename }}"
_truststores_template:
  keyStoreName: "{{ lookup('env', 'settings_truststores_%s_name' | format(index_item)) | default('',true) }}"
  keyStoreDescription: "{{ lookup('env', 'settings_truststores_%s_description' | format(index_item)) | default('',true) }}"
  keyStoreType: "{{ lookup('env', 'settings_truststores_%s_type' | format(index_item)) | default('',true) }}"
  keyStoreProvider: "{{ lookup('env', 'settings_truststores_%s_provider' | format(index_item)) | default('',true) }}"
  keyStorePassword: "{{ lookup('env', 'settings_truststores_%s_password' | format(index_item)) | default('',true) | b64encode }}"
  isPwdBase64Encoded: "true"
  uploadFileName: "{{ _truststores_template_filename }}"
  fileContent: "@{{ _truststores_template_filepath }}"
