---

vars_ssl_inbound_outbound_enabled: "{{ lookup('env', 'settings_ssl_inbound_outbound_configure') | default('false',true) }}"
vars_ssl_inbound_outbound_ignore_errors: "{{ lookup('env', 'settings_ssl_inbound_outbound_configure_ignore_errors') | default(vars_default_ignore_errors,true) }}"

## apigateway keystore/truststore setup for inbound and outbound messages
vars_rest_ssl_inbound_outbound_configuration:
  keystoreName: "{{ lookup('env', 'settings_ssl_inbound_keystore_name') | default('',true) }}"
  signingAlias: "{{ lookup('env', 'settings_ssl_inbound_keystore_keyalias') | default('',true) }}"
  truststoreName: "{{ lookup('env', 'settings_ssl_inbound_truststore_name') | default('',true) }}"
  outboundKeystoreName: "{{ lookup('env', 'settings_ssl_outbound_keystore_name') | default('',true) }}"
  outboundKeyAlias: "{{ lookup('env', 'settings_ssl_outbound_keystore_keyalias') | default('',true) }}"
  outboundTruststoreName: "{{ lookup('env', 'settings_ssl_outbound_truststore_name') | default('',true) }}"
