---

vars_apigw_keystore_enabled: "{{ lookup('env', 'apigw_settings_keystore_configure') | default('false',true) }}"
vars_apigw_keystore_ignore_errors: "{{ lookup('env', 'apigw_settings_keystore_configure_ignore_errors') | default(vars_apigw_default_ignore_errors,true) }}"

vars_apigw_truststore_enabled: "{{ lookup('env', 'apigw_settings_truststore_configure') | default('false',true) }}"
vars_apigw_truststore_ignore_errors: "{{ lookup('env', 'apigw_settings_truststore_configure_ignore_errors') | default(vars_apigw_default_ignore_errors,true) }}"

## apigateway keystore / truststore details
vars_apigw_keystore_filepath: "{{ lookup('env', 'apigw_settings_keystore_filepath') | default('',true) }}"
vars_apigw_keystore_filename: "{{ vars_apigw_keystore_filepath | basename }}"
vars_apigw_keystore_name: "{{ lookup('env', 'apigw_settings_keystore_name') | default((vars_apigw_keystore_filename | splitext)[0],true) }}"
vars_apigw_keystore_keyalias_name: "{{ lookup('env', 'apigw_settings_keystore_keyalias') | default('',true) }}"
vars_apigw_keystore:
  filepath: "{{ vars_apigw_keystore_filepath }}"
  filename: "{{ vars_apigw_keystore_filename }}"
  name: "{{ vars_apigw_keystore_name }}"
  type: "{{ lookup('env', 'apigw_settings_keystore_type') | default('JKS',true) }}"
  provider: "{{ lookup('env', 'apigw_settings_keystore_provider') | default('SUN',true) }}"
  description: "{{ lookup('env', 'apigw_settings_keystore_description') | default('APIGateway keystore',true) }}"
  password: "{{ lookup('env', 'apigw_settings_keystore_password') | default('',true) }}"
  keyalias:  "{{ vars_apigw_keystore_keyalias_name }}"
  keyalias_password: "{{ lookup('env', 'apigw_settings_keystore_keyalias_password') | default('',true) }}"

vars_apigw_truststore_filepath: "{{ lookup('env', 'apigw_settings_truststore_filepath') | default('',true) }}"
vars_apigw_truststore_filename: "{{ vars_apigw_truststore_filepath | basename }}"
vars_apigw_truststore_name: "{{ lookup('env', 'apigw_settings_truststore_name') | default((vars_apigw_truststore_filename | splitext)[0],true) }}"
vars_apigw_truststore:
  filepath: "{{ vars_apigw_truststore_filepath }}"
  filename: "{{ vars_apigw_truststore_filename }}"
  name: "{{ vars_apigw_truststore_name }}"
  type: "{{ lookup('env', 'apigw_settings_truststore_type') | default('JKS',true) }}"
  provider: "{{ lookup('env', 'apigw_settings_truststore_provider') | default('SUN',true) }}"
  description: "{{ lookup('env', 'apigw_settings_truststore_description') | default('APIGateway truststore',true) }}"
  password: "{{ lookup('env', 'apigw_settings_truststore_password') | default('',true) }}"

############################################################
##### the vars for the rest calls
############################################################

## apigateway truststore details
vars_apigw_rest_ssl_truststore:
  keyStoreName: "{{ vars_apigw_truststore.name }}"
  keyStoreType: "{{ vars_apigw_truststore.type }}"
  keyStoreProvider: "{{ vars_apigw_truststore.provider }}"
  keyStorePassword: "{{ vars_apigw_truststore.password | b64encode }}"
  uploadFileName: "{{ vars_apigw_truststore.filename }}"
  keyStoreDescription: "{{ vars_apigw_truststore.description }}"
  fileContent: "@{{ vars_apigw_truststore.filepath }}"
  isPwdBase64Encoded: "true"

## apigateway keystore details
## pkAliasesList: Comma separated list of alias names in the uploaded keystore file.
## pkPasswordsList: Comma separated list of passwords in the same order as the aliases specified in pkAliasesList. If a particular key alias does not have a password, it is denoted by space.
## nullPKpasswds: Comma separated list of boolean values (true/false) indicating whether the particular alias has a password or not in the same order as the aliases specified in pkAliasesList. For each key alias, true indicates that the key alias does not have a password and false indicates that it does have a password.
vars_apigw_rest_ssl_keystore:
  keyStoreName: "{{ vars_apigw_keystore.name }}"
  keyStoreType: "{{ vars_apigw_keystore.type }}"
  keyStoreProvider: "{{ vars_apigw_keystore.provider }}"
  keyStorePassword: "{{ vars_apigw_keystore.password | b64encode }}"
  uploadFileName: "{{ vars_apigw_keystore.filename }}"
  keyStoreDescription: "{{ vars_apigw_keystore.description }}"
  fileContent: "@{{ vars_apigw_keystore.filepath }}"
  isPwdBase64Encoded: "true"

# this is for the aliases inside the keystore
vars_apigw_rest_ssl_keystore_keyalias_list:
  - keyStoreName: "{{ vars_apigw_keystore.name }}"
    nullPKpasswds: "false"
    isPwdBase64Encoded: "false"
    bitarray: "1"
    pkAliasesList: "{{ vars_apigw_keystore.keyalias }}"
    pkPasswordsList: "{{ vars_apigw_keystore.keyalias_password }}"