---

vars_keystores_enabled: "{{ lookup('env', 'settings_keystores_configure') | default('false',true) }}"
vars_keystores_ignore_errors: "{{ lookup('env', 'settings_keystores_configure_ignore_errors') | default(vars_default_ignore_errors,true) }}"

_keystores_indices_finder_prefix: "settings_keystores_"
_keystores_indices_finder_suffix: "_name"
_index_items_regex_pattern: "{{ common_index_items_regex_pattern | format( _keystores_indices_finder_prefix, _keystores_indices_finder_suffix) }}"

_keystores_template_filepath: "{{ lookup('env', 'settings_keystores_%s_filepath' | format(index_item)) | default('',true) }}"
_keystores_template_filename: "{{ _keystores_template_filepath | basename }}"

# IMPORTANT: if isPwdBase64Encoded=true, all password MUST be encoded or it will error out
# also, for pkPasswordsList, each password in the comma-separated list would need to be encoded 
# TODO: --> need to post process this -- in the meantime, let's set isPwdBase64Encoded=false for now
_keystores_template:
  keyStoreName: "{{ lookup('env', 'settings_keystores_%s_name' | format(index_item)) | default('',true) }}"
  keyStoreDescription: "{{ lookup('env', 'settings_keystores_%s_description' | format(index_item)) | default('',true) }}"
  keyStoreType: "{{ lookup('env', 'settings_keystores_%s_type' | format(index_item)) | default('',true) }}"
  keyStoreProvider: "{{ lookup('env', 'settings_keystores_%s_provider' | format(index_item)) | default('',true) }}"
  keyStorePassword: "{{ lookup('env', 'settings_keystores_%s_password' | format(index_item)) | default('',true) }}"
  uploadFileName: "{{ _keystores_template_filename }}"
  fileContent: "@{{ _keystores_template_filepath }}"
  pkAliasesList: "{{ lookup('env', 'settings_keystores_%s_aliases' | format(index_item)) | default('',true) }}"
  pkPasswordsList: "{{ lookup('env', 'settings_keystores_%s_aliasesPasswords' | format(index_item)) | default('',true) }}"
  nullPKpasswds: "{{ lookup('env', 'settings_keystores_%s_aliasesPasswordsNull' | format(index_item)) | default('',true) }}"
  isPwdBase64Encoded: "false"