---

vars_apigw_truststores_enabled: "{{ lookup('env', 'apigw_settings_truststores_configure') | default('false',true) }}"
vars_apigw_truststores_ignore_errors: "{{ lookup('env', 'apigw_settings_truststores_configure_ignore_errors') | default(vars_apigw_default_ignore_errors,true) }}"

_apigw_truststores_indices_finder_prefix: "apigw_settings_truststores_"
_apigw_truststores_indices_finder_suffix: "_name"
_index_items_regex_pattern: "{{ common_index_items_regex_pattern | format( _apigw_truststores_indices_finder_prefix, _apigw_truststores_indices_finder_suffix) }}"

_apigw_truststores_template_filepath: "{{ lookup('env', 'apigw_settings_truststores_%s_filepath' | format(index_item)) | default('',true) }}"
_apigw_truststores_template_filename: "{{ _apigw_truststores_template_filepath | basename }}"
_apigw_truststores_template:
  keyStoreName: "{{ lookup('env', 'apigw_settings_truststores_%s_name' | format(index_item)) | default('',true) }}"
  keyStoreDescription: "{{ lookup('env', 'apigw_settings_truststores_%s_description' | format(index_item)) | default('',true) }}"
  keyStoreType: "{{ lookup('env', 'apigw_settings_truststores_%s_type' | format(index_item)) | default('',true) }}"
  keyStoreProvider: "{{ lookup('env', 'apigw_settings_truststores_%s_provider' | format(index_item)) | default('',true) }}"
  keyStorePassword: "{{ lookup('env', 'apigw_settings_truststores_%s_password' | format(index_item)) | default('',true) | b64encode }}"
  isPwdBase64Encoded: "true"
  uploadFileName: "{{ _apigw_truststores_template_filename }}"
  fileContent: "@{{ _apigw_truststores_template_filepath }}"
