---

################################################################
## set configs via REST APIs
################################################################

- name: Sample data config tasks
  hosts: local
  become: true
  become_user: "{{ webmethods_user }}"
  run_once: true
  vars:
    apigateway_rest_protocol: "{{ vars_apigateway_rest_protocol }}"
    apigateway_rest_host: "{{ vars_apigateway_rest_host }}"
    apigateway_rest_port: "{{ vars_apigateway_rest_port }}"
    apigateway_rest_no_check_certs: "{{ vars_apigateway_rest_no_check_certs }}"
    apigateway_rest_login_username: "{{ vars_apigateway_rest_login_username }}"
    apigateway_rest_login_password: "{{ vars_apigateway_rest_login_password }}"

  tasks:

    ## printing the vars that enable/disable the roles
    - block:
        - debug: var=vars_webmethods_apigateway_usermgt_enabled verbosity=3
        - debug: var=vars_webmethods_apigateway_archive_imports_enabled verbosity=3
        - debug: var=vars_webmethods_apigateway_aliases_enabled verbosity=3
        - debug: var=vars_webmethods_apigateway_applications_enabled verbosity=3
        - debug: var=vars_webmethods_apigateway_plans_enabled verbosity=3
        - debug: var=vars_webmethods_apigateway_packages_enabled verbosity=3
      tags: always

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_usermgt_ignore_errors }}"
      vars:
        configs_action: set-users
        configs_enabled: "{{ vars_webmethods_apigateway_usermgt_enabled }}"
        apigateway_configparams_rest_usermgt_users: "{{ vars_webmethods_apigateway_usermgt_users }}"
      tags:
        - configs_users

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_usermgt_ignore_errors }}"
      vars:
        configs_action: set-groups
        configs_enabled: "{{ vars_webmethods_apigateway_usermgt_enabled }}"
        apigateway_configparams_rest_usermgt_groups: "{{ vars_webmethods_apigateway_usermgt_groups }}"
      tags:
        - configs_groups

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_usermgt_ignore_errors }}"
      vars:
        configs_action: set-accessprofiles
        configs_enabled: "{{ vars_webmethods_apigateway_usermgt_enabled }}"
        apigateway_configparams_rest_usermgt_accessprofiles: "{{ vars_webmethods_apigateway_usermgt_accessprofiles }}"
      tags:
        - configs_accessprofiles

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_aliases_ignore_errors }}"
      vars:
        configs_action: set-aliases
        configs_enabled: "{{ vars_webmethods_apigateway_aliases_enabled }}"
        rvar_apigateway_aliases: "{{ vars_webmethods_apigateway_aliases }}"
      tags:
        - configs_aliases

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_archive_imports_ignore_errors }}"
      vars:
        configs_action: import-archive-from-s3
        configs_enabled: "{{ vars_webmethods_apigateway_archive_imports_enabled }}"
        rvar_apigateway_archive_imports_s3_downloads: "{{ vars_webmethods_apigateway_archive_imports_from_s3 }}"
      tags:
        - configs_archives

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_applications_ignore_errors }}"
      vars:
        configs_action: set-applications
        configs_enabled: "{{ vars_webmethods_apigateway_applications_enabled }}"
        rvar_apigateway_applications: "{{ vars_webmethods_apigateway_applications }}"
      tags:
        - configs_applications

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_plans_ignore_errors }}"
      vars:
        configs_action: set-plans
        configs_enabled: "{{ vars_webmethods_apigateway_plans_enabled }}"
        rvar_apigateway_plans: "{{ vars_webmethods_apigateway_plans }}"
      tags:
        - configs_plans

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_packages_ignore_errors }}"
      vars:
        configs_action: set-packages
        configs_enabled: "{{ vars_webmethods_apigateway_packages_enabled }}"
        rvar_apigateway_packages: "{{ vars_webmethods_apigateway_packages }}"
      tags:
        - configs_packages

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_apis_publish_groups_ignore_errors }}"
      vars:
        configs_action: publish-apis-groups
        configs_enabled: "{{ vars_webmethods_apigateway_apis_publish_groups_enabled }}"
        rvar_apigateway_apis_publish_groups: "{{ vars_webmethods_apigateway_apis_publish_groups }}"
      tags:
        - publish_apis

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_packages_publish_groups_ignore_errors }}"
      vars:
        configs_action: publish-packages-groups
        configs_enabled: "{{ vars_webmethods_apigateway_packages_publish_groups_enabled }}"
        rvar_apigateway_packages_publish_groups: "{{ vars_webmethods_apigateway_packages_publish_groups }}"
      tags:
        - publish_packages

    - name: final package deactivate
      include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_webmethods_apigateway_packages_ignore_errors }}"
      vars:
        configs_action: activate-packages
        configs_enabled: "{{ vars_webmethods_apigateway_packages_enabled }}"
        rvar_apigateway_packages: "{{ vars_webmethods_apigateway_packages_update_final_status }}"
      tags:
        - configs_packages