---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/settings_lb_urls.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  become: true
  become_user: "{{ webmethods_user }}"
  run_once: true
  vars:
    apigateway_rest_protocol: "{{ vars_apigw_rest_protocol }}"
    apigateway_rest_host: "{{ vars_apigw_rest_host }}"
    apigateway_rest_port: "{{ vars_apigw_rest_port }}"
    apigateway_rest_no_check_certs: "{{ vars_apigw_rest_no_check_certs }}"
    apigateway_rest_login_username: "{{ vars_apigw_rest_login_username }}"
    apigateway_rest_login_password: "{{ vars_apigw_rest_login_password }}"

  tasks:

    - name: set initial list so it's not undefined
      set_fact:
         _http_urls: "{{ _apigw_settings_lburls_http_urls.split(';')|map('trim')|select()|list }}"
         _https_urls: "{{ _apigw_settings_lburls_https_urls.split(';')|map('trim')|select()|list }}"
         _websocket_urls: "{{ _apigw_settings_lburls_websocket_urls.split(';')|map('trim')|select()|list }}"

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_apigw_loadbalancer_ignore_errors }}"
      vars:
        configs_action: set-loadbalancer-urls
        configs_enabled: "{{ vars_apigw_loadbalancer_enabled }}"
        webmethods_apigateway_loadbalancers_http_urls: "{{ _http_urls }}"
        webmethods_apigateway_loadbalancers_https_urls: "{{ _https_urls }}"
        webmethods_apigateway_loadbalancers_websocket_urls: "{{ _websocket_urls }}"
        webmethods_apigateway_loadbalancers_webapp_url: "{{ _apigw_settings_lburls_webapp_url }}"
