---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/connection.yaml
        - vars/loadbalancer_urls.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  become: true
  become_user: "{{ webmethods_user }}"
  run_once: true
  vars:
    apigateway_rest_protocol: "{{ vars_apigw_rest_protocol }}"
    apigateway_rest_host: "{{ vars_apigw_rest_host }}"
    apigateway_rest_port: "{{ vars_apigw_rest_port }}"
    apigateway_rest_no_check_certs: "{{ vars_apigw_rest_no_check_certs }}"
    apigateway_rest_login_username: "{{ vars_apigw_rest_login_username }}"
    apigateway_rest_login_password: "{{ vars_apigw_rest_login_password }}"

  tasks:

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_apigw_loadbalancer_ignore_errors }}"
      vars:
        configs_action: set-loadbalancer-urls
        configs_enabled: "{{ vars_apigw_loadbalancer_enabled }}"
        webmethods_apigateway_loadbalancers_http_urls: "{{ vars_apigw_loadbalancers_http_urls }}"
        webmethods_apigateway_loadbalancers_https_urls: "{{ vars_apigw_loadbalancers_https_urls }}"
        webmethods_apigateway_loadbalancers_websocket_urls: "{{ vars_apigw_loadbalancers_websocket_urls }}"
        webmethods_apigateway_loadbalancers_webapp_url: "{{ vars_apigw_loadbalancers_webapp_url }}"
      tags:
        - configs_loadbalancer_urls
