---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/data_aliases.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  become: true
  become_user: "{{ webmethods_user }}"
  run_once: true
  vars:
    apigateway_rest_protocol: "{{ vars_apigw_rest_protocol }}"
    apigateway_rest_host: "{{ vars_apigw_rest_host }}"
    apigateway_rest_port: "{{ vars_apigw_rest_port }}"
    apigateway_rest_no_check_certs: "{{ vars_apigw_rest_no_check_certs }}"
    apigateway_rest_login_username: "{{ vars_apigw_rest_login_username }}"
    apigateway_rest_login_password: "{{ vars_apigw_rest_login_password }}"

  tasks:

    - name: init the list
      set_fact:
        vars_apigw_aliases_list: []

    - ansible.builtin.debug:
        msg: "{{ item }}"
      # range is exclusive of the end point
      loop: "{{ range(1, vars_apigw_aliases_count | int, 1)|list }}"

    - name: append item
      set_fact:
        vars_apigw_aliases_list: "{{ vars_apigw_aliases_list }} + [ vars_apigw_aliases_simple_item ]"
      loop: "{{ range(1, vars_apigw_aliases_count | int, 1)|list }}"

    - ansible.builtin.debug:
        var: vars_apigw_aliases_list

    # - include_role:
    #     name: apigateway-rest-configurator
    #     apply:
    #       ignore_errors: "{{ vars_apigw_aliases_ignore_errors }}"
    #   vars:
    #     configs_action: set-aliases
    #     configs_enabled: "{{ vars_apigw_aliases_enabled }}"
    #     rvar_apigateway_aliases: "{{ vars_apigw_aliases }}"