---

- ansible.builtin.debug:
    var: "{{ item }}"
  loop:
    - _apigw_applications_identifiers_index_items_regex_pattern
    - _apigw_applications_identifiers_index_items

- name: set initial list so it's not undefined and it's back to empty on each iteration
  set_fact:
    _application_identifiers_list: []

- name: append each item template to list
  set_fact:
    _application_identifiers_list: "{{ _application_identifiers_list + [ _apigw_applications_identifiers_template ] }}"
  loop: "{{ _apigw_applications_identifiers_index_items }}"
  loop_control:
    loop_var: identifiers_index_item

- ansible.builtin.debug:
    var: _application_identifiers_list
