---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/settings_lb_urls.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  tasks:

    - include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: set-loadbalancer-urls
        configs_enabled: "{{ vars_loadbalancer_enabled }}"
        rvar_apigateway_loadbalancers_http_urls: "{{ _settings_lburls_http_urls }}"
        rvar_apigateway_loadbalancers_https_urls: "{{ _settings_lburls_https_urls }}"
        rvar_apigateway_loadbalancers_websocket_urls: "{{ _settings_lburls_websocket_urls }}"
        rvar_apigateway_loadbalancers_webapp_url: "{{ _settings_lburls_webapp_url }}"
