---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/data_plans.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  become: true
  become_user: "{{ webmethods_user }}"
  run_once: true
  vars:
    apigateway_rest_protocol: "{{ vars_apigw_rest_protocol }}"
    apigateway_rest_host: "{{ vars_apigw_rest_host }}"
    apigateway_rest_port: "{{ vars_apigw_rest_port }}"
    apigateway_rest_no_check_certs: "{{ vars_apigw_rest_no_check_certs }}"
    apigateway_rest_login_username: "{{ vars_apigw_rest_login_username }}"
    apigateway_rest_login_password: "{{ vars_apigw_rest_login_password }}"

  tasks:

    - name: get the count of items from the env vars
      set_fact:
        _index_items: "{{ ansible_env.keys() | map('regex_search','^apigw_data_plans_(.+)_name$', '\\1') | select('string') | list | unique  }}"

    - ansible.builtin.debug:
        var: _index_items

    - name: append each item template to list
      set_fact:
        _plans_list: "{{ _plans_list | default([]) + [ _apigw_plans_template ] }}"
      loop: "{{ _index_items }}"
      loop_control:
        loop_var: index_item

    - ansible.builtin.debug:
        var: _plans_list

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: "{{ vars_apigw_plans_ignore_errors }}"
      vars:
        configs_action: set-plans
        configs_enabled: "{{ vars_apigw_plans_enabled }}"
        rvar_apigateway_plans: "{{ _plans_list }}"
