---

- name: get the current alias type
  set_fact:
    _item_type: "{{ lookup('env', 'apigw_data_aliases_%d_type' | format(index_item)) | default('') | lower }}"

- name: fail if _item_type is not specified
  fail: 
    msg: "_item_type not defined, cannot do anything."
  when: _item_type is not defined or _item_type == ""

- name: select the right item template based on type
  set_fact:
    _item: "{{ _apigw_aliases_template_simple_alias }}"
  when: _item_type == 'simple'

- name: select the right item template based on type
  set_fact:
    _item: "{{ _apigw_aliases_template_endpoint_alias }}"
  when: _item_type == 'endpoint'

- name: append each alias item to list
  set_fact:
    _aliases_list: "{{ _aliases_list | default([]) + [ _item ] }}"
  when: _item is defined