---

- name: set intial items so they are back to empty / reset on each iteration
  set_fact:
    _item: "{{ _apis_template }}"
    _api_tags: []

############ apply tags

- name: transform tags into expected format
  set_fact:
    _api_tags: "{{ _api_tags + [ { 'name': item } ] }}"
  loop: "{{ _apis_template_tags }}"

- name: Assign the api patch
  set_fact:
    _item: "{{ _item | combine( _api_tags_patch,recursive=True ) }}"
  vars:
    _api_tags_patch: 
      apiDefinition:
        tags: "{{ _api_tags }}"

############ final add to list
- name: append item to list
  set_fact:
    _apis_list: "{{ _apis_list | default([]) + [ _item ] }}"
  when: _item is defined
